I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 272, in script
    python:
  File "game/script.rpy", line 276, in <module>
    renpy.store.tool_call_counts[data.get("function")]+=1
KeyError: None

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 272, in script
    python:
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 276, in <module>
    renpy.store.tool_call_counts[data.get("function")]+=1
KeyError: None

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Ushio_Noa 0.1.0_beta
Fri Dec 27 23:20:24 2024
