I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 365, in script call
    python:
  File "game/script.rpy", line 365, in script call
    python:
  File "game/script.rpy", line 322, in script
    python:
  File "game/script.rpy", line 348, in <module>
    while not tts.ready:
AttributeError: 'Audio_generator' object has no attribute 'ready'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 365, in script call
    python:
  File "game/script.rpy", line 365, in script call
    python:
  File "game/script.rpy", line 322, in script
    python:
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 348, in <module>
    while not tts.ready:
AttributeError: 'Audio_generator' object has no attribute 'ready'

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Ushio_Noa 0.1.0_beta
Thu Dec 26 03:16:03 2024
