I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script
    scene default_background with fit
  File "game/script.rpy", line 48, in <module>
    scene default_background with fit
NameError: name 'fit' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script
    scene default_background with fit
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\water\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 48, in <module>
    scene default_background with fit
NameError: name 'fit' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Ushio_Noa 0.1.0_beta
Thu Nov 21 21:38:16 2024
